### ISSUE TITLE
破壊的変更

### ISSUE THREAD

**Issue by Takeky0** [Takeky0/MissingByte#5]
#s->LsとVsする
Ls:サブリスト　破壊的変更なし
Vs:変数 破壊的変更しかできない
Vsに対する$sと&sは
$s->sの保持情報が消える=変数sというもの自体が消える
&s->sの保持情報をそのままにする=変数sは消えない
こんなもんかね
そうすると#が浮くから、
文字列で型を文字列から数字またその逆も#で変更できればなと
("1.23"#->1.23 , 4#->"4")

**Comment by yuruhi** [comment]
- 変数参照の方を `$` にした方が直感にあってる気がする
 - 数値↔文字列のキャストを1つのコマンドにすると数値か文字列かわからない場合にキャストしようとすると困るので分けた方がいい

**Comment by Takeky0** [comment]
$と&はどちらでも
じゃあ#をC(文字列に変更),N(数値に変更)に分けますか
そうなったときに、どこに#を持っていくか

**Comment by yuruhi** [comment]
<code> @<em>a</em> </code>
